// Generated by https://EmojiGeneratorAPI.Models.io
using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace EmojiGeneratorAPI.Models
{

    public partial class Emoji
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("category")]
        public string Category { get; set; }

        [JsonProperty("group")]
        public string Group { get; set; }

        [JsonProperty("htmlCode")]
        public string[] HtmlCode { get; set; }

        [JsonProperty("unicode")]
        public string[] Unicode { get; set; }
    }

    public partial class Emoji
    {
        public static Emoji FromJson(string json) => JsonConvert.DeserializeObject<Emoji>(json, EmojiGeneratorAPI.Models.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Emoji self) => JsonConvert.SerializeObject(self, EmojiGeneratorAPI.Models.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
